apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchbase-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: couchbase-master
    spec:
      containers:
        - name: couchbase-master
          image: couchbase:latest
          ports:
             - containerPort: 8091

---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-master-service
spec:
  ports:
  - port: 8091
    nodePort: 30091
  type: NodePort
  selector:
    run: couchbase-master
