apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clojure-rest-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: clojure-rest-example
    spec:
      containers:
        - name: clojure-rest-example
          image: clojure-rest-example:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: "example-mongodb"
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_NAME
              value: "test-db"
          ports:
            - containerPort: 3000
