apiVersion: v1
kind: Service
metadata:
  name: clojure-rest-example-svc
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30060
  selector:
    run: clojure-rest-example
